# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20200219_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
