# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-25 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_auto_20200224_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='date_posted',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
