# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_auto_20200226_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='time_ending',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='time_starting',
        ),
        migrations.AddField(
            model_name='artifact',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.TextField(max_length=210),
        ),
    ]
