# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-27 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_auto_20200226_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='quantity',
        ),
        migrations.AddField(
            model_name='artifact',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
